apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskconsumer
spec:
  selector:
    matchLabels:
      app: flaskconsumer
  template:
    metadata:
      labels:
        app: flaskconsumer
    spec:
      containers:
      - name: flaskconsumer
        image: winatan/flaskconsumer
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
 name: flaskconsumer
spec:
 type: NodePort
 selector:
   app: flaskconsumer
 ports:
 - port: 80
   targetPort: 5000
   nodePort: 31289